=== ihofmann/open-websoccer/websoccer/modules/module.dtd
<!ELEMENT module (admin?|settings?|pages?|dependencies?|blocks?|actions?|plugins?)*>
<!ATTLIST module version CDATA #REQUIRED>

<!ELEMENT dependencies (dependency+)>
<!ELEMENT dependency EMPTY>
<!ATTLIST dependency module CDATA #REQUIRED>
<!ATTLIST dependency version CDATA #REQUIRED>

<!ELEMENT admin (adminpage+)>

<!ELEMENT adminpage (entity?)>
<!ATTLIST adminpage id CDATA #REQUIRED>
<!ATTLIST adminpage navcategory CDATA #REQUIRED>
<!ATTLIST adminpage entity CDATA #IMPLIED>
<!ATTLIST adminpage permissionrole (r_admin|r_daten|r_adminuser|r_news|r_spiele|r_user) #IMPLIED>
<!ATTLIST adminpage filename CDATA #IMPLIED>

<!ELEMENT entity (overview, editform?)>
<!ATTLIST entity dbtable CDATA #REQUIRED>

<!ELEMENT overview (column+, join*)>
<!ATTLIST overview add (true|false) "true">
<!ATTLIST overview edit (true|false) "false">
<!ATTLIST overview delete (true|false) "false">
<!ATTLIST overview logging (true|false) "false">
<!ATTLIST overview loggingcolumns CDATA #IMPLIED>

<!ELEMENT column EMPTY>
<!ATTLIST column id CDATA #REQUIRED>
<!ATTLIST column filter (true|false) "false">
<!ATTLIST column sort (true|false) "false">
<!ATTLIST column type (text|number|email|boolean|select|timestamp|percent|fk) #REQUIRED>
<!ATTLIST column field CDATA #REQUIRED>
<!ATTLIST column selection CDATA #IMPLIED>
<!ATTLIST column converter CDATA #IMPLIED>
<!ATTLIST column hidden (true|false) "false">

<!ELEMENT join EMPTY>
<!ATTLIST join type (LEFT|INNER|RIGHT) #REQUIRED>
<!ATTLIST join jointable CDATA #REQUIRED>
<!ATTLIST join joincondition CDATA #REQUIRED>

<!ELEMENT editform (field+)>

<!ELEMENT field EMPTY>
<!ATTLIST field id CDATA #REQUIRED>
<!ATTLIST field required (true|false) "false">
<!ATTLIST field editonly (true|false) "false">
<!ATTLIST field type (text|number|email|boolean|password|url|select|textarea|file|timestamp|color|date|percent|foreign_key) #REQUIRED>
<!ATTLIST field converter CDATA #IMPLIED>
<!ATTLIST field validator CDATA #IMPLIED>
<!ATTLIST field entity CDATA #IMPLIED>
<!ATTLIST field jointable CDATA #IMPLIED>
<!ATTLIST field cascade CDATA #FIXED "delete">
<!ATTLIST field labelcolumns CDATA #IMPLIED>
<!ATTLIST field selection CDATA #IMPLIED>
<!ATTLIST field roles CDATA #IMPLIED>
<!ATTLIST field readonly (true|false) "false">
<!ATTLIST field default CDATA #IMPLIED>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting id CDATA #REQUIRED>
<!ATTLIST setting type (text|number|email|boolean|password|url|select|textarea|timestamp|foreign_key|tags) #REQUIRED>
<!ATTLIST setting category CDATA #IMPLIED>
<!ATTLIST setting default CDATA #IMPLIED>
<!ATTLIST setting selection CDATA #IMPLIED>

<!ELEMENT pages (page+)>

<!ELEMENT page (page*, script*, css*)>
<!ATTLIST page id CDATA #REQUIRED>
<!ATTLIST page template CDATA #REQUIRED>
<!ATTLIST page role CDATA #REQUIRED>
<!ATTLIST page model CDATA #IMPLIED>
<!ATTLIST page parentItem CDATA #IMPLIED>
<!ATTLIST page navweight CDATA #IMPLIED>
<!ATTLIST page navitem (true|false) "false">
<!ATTLIST page navmenukey CDATA #IMPLIED>
<!ATTLIST page navitemOnlyForConfigEnabled CDATA #IMPLIED>
<!ATTLIST page premiumBalanceMin CDATA #IMPLIED>

<!ELEMENT script EMPTY>
<!ATTLIST script file CDATA #REQUIRED>
<!ATTLIST script debugonly (true|false) "false">
<!ATTLIST script productiononly (true|false) "false">

<!ELEMENT css EMPTY>
<!ATTLIST css file CDATA #REQUIRED>
<!ATTLIST css debugonly (true|false) "false">
<!ATTLIST css productiononly (true|false) "false">

<!ELEMENT blocks (block+)>

<!ELEMENT block EMPTY>
<!ATTLIST block id CDATA #REQUIRED>
<!ATTLIST block template CDATA #REQUIRED>
<!ATTLIST block role CDATA #REQUIRED>
<!ATTLIST block model CDATA #IMPLIED>
<!ATTLIST block includepages CDATA #IMPLIED>
<!ATTLIST block area (sidebar|content_top|content_bottom|custom) #IMPLIED>
<!ATTLIST block weight CDATA #IMPLIED>
<!ATTLIST block excludepages CDATA #IMPLIED>
<!ATTLIST block premiumBalanceMin CDATA #IMPLIED>

<!ELEMENT actions (action+)>

<!ELEMENT action (param*)>
<!ATTLIST action id CDATA #REQUIRED>
<!ATTLIST action role CDATA #REQUIRED>
<!ATTLIST action controller CDATA #REQUIRED>
<!ATTLIST action premiumBalanceMin CDATA #IMPLIED>
<!ATTLIST action log (true|false) "false">

<!ELEMENT param EMPTY>
<!ATTLIST param id CDATA #REQUIRED>
<!ATTLIST param type (text|number|email|boolean|password|date|url|percent) #REQUIRED>
<!ATTLIST param required (true|false) "false">
<!ATTLIST param min CDATA #IMPLIED>
<!ATTLIST param max CDATA #IMPLIED>
<!ATTLIST param validator CDATA #IMPLIED>

<!ELEMENT plugins (eventlistener+)>

<!ELEMENT eventlistener EMPTY>
<!ATTLIST eventlistener event CDATA #REQUIRED>
<!ATTLIST eventlistener class CDATA #REQUIRED>
<!ATTLIST eventlistener method CDATA #REQUIRED>

=== ihofmann/open-websoccer/websoccer/modules/players/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="5.1.1">

    <dependencies>
        <dependency module="clubs" version="1.0.0"/>
    </dependencies>
    
    <admin>
        <adminpage
            id="player"
            entity="player"
            navcategory="league"
            permissionrole="r_daten" >

            <entity dbtable="spieler AS PlayerTab" >

                <overview delete="true" edit="true" logging="true" loggingcolumns="vorname,nachname,kunstname,verein_id,position">

                    <column
                        id="entity_player_nachname"
                        field="PlayerTab.nachname"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_player_vorname"
                        field="PlayerTab.vorname"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_player_kunstname"
                        field="PlayerTab.kunstname"
                        type="text"
                        sort="true"
                        filter="true" />

                    <column
                        id="entity_player_verein_id"
                        field="ClubTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_player_position"
                        field="PlayerTab.position"
                        type="text"
                        sort="true" />
                    
                     <column
                        id="entity_player_position_main"
                        field="PlayerTab.position_main"
                        type="text"
                        sort="true" />
                     
                     <column
                        id="entity_player_position_second"
                        field="PlayerTab.position_second"
                        type="text"
                        sort="true" />
                     
                     <column
                        id="entity_player_lending_owner_id"
                        field="LenderTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_player_status"
                        field="PlayerTab.status"
                        type="boolean" />
                    
                	<join type="LEFT" jointable="verein AS ClubTab" joincondition="PlayerTab.verein_id = ClubTab.id" />
                	<join type="LEFT" jointable="verein AS LenderTab" joincondition="PlayerTab.lending_owner_id = LenderTab.id" />
                </overview>

                <editform>
                    <field id="vorname" type="text" />
					<field id="nachname" type="text" />
					<field id="kunstname" type="text" />
					<field id="verein_id" type="foreign_key" entity="club" jointable="verein" cascade="delete" labelcolumns="name" />
					<field id="geburtstag" type="date"  />
					<field id="age" type="number"  />
					<field id="position" type="select" selection="Torwart,Abwehr,Mittelfeld,Sturm" required="true"  />
					<field id="position_main" type="select" selection="T,LV,IV,RV,LM,ZM,DM,OM,RM,LS,MS,RS" required="false"  />
					<field id="position_second" type="select" selection="T,LV,IV,RV,LM,ZM,DM,OM,RM,LS,MS,RS" required="false"  />
					<field id="nation" type="text" required="true"  />
					
					<field id="picture" type="file"  />
					<field id="verletzt" type="number" default="0" />
					<field id="gesperrt" type="number" default="0"  />
					<field id="gesperrt_cups" type="number" default="0"  />
					<field id="gesperrt_nationalteam" type="number" default="0"  />
					
					<field id="w_staerke" type="percent" required="true" roles="r_staerken" />
					<field id="w_technik" type="percent" required="true" roles="r_staerken" />
					<field id="w_kondition" type="percent" required="true" roles="r_staerken" />
					<field id="w_frische" type="percent" required="true" roles="r_staerken" />
					<field id="w_zufriedenheit" type="percent" required="true" roles="r_staerken" />
					
					<field id="transfermarkt" type="boolean" />
					<field id="transfer_start" type="timestamp" />
					<field id="transfer_ende" type="timestamp" />
					<field id="transfer_mindestgebot" type="number" />
					
					<field id="vertrag_gehalt" type="number" />
					<field id="vertrag_spiele" type="number" />
					<field id="vertrag_torpraemie" type="number" />
					
					<field id="lending_owner_id" type="foreign_key" entity="club" jointable="verein" labelcolumns="name" />
					<field id="lending_fee" type="number" />
					<field id="lending_matches" type="number" />
					
					<field id="marktwert" type="number" />
					
					<field id="sa_tore" type="number" />
					<field id="sa_assists" type="number" />
					<field id="sa_spiele" type="number" />
					<field id="sa_karten_gelb" type="number" />
					<field id="sa_karten_gelb_rot" type="number" />
					<field id="sa_karten_rot" type="number" />
					
					<field id="st_tore" type="number" />
					<field id="st_assists" type="number" />
					<field id="st_spiele" type="number" />
					<field id="st_karten_gelb" type="number" />
					<field id="st_karten_gelb_rot" type="number" />
					<field id="st_karten_rot" type="number" />
					
					<field id="history" type="textarea" />
					
					<field id="unsellable" type="boolean" />
					<field id="status" type="boolean" default="1" />
                </editform>
            </entity>
        </adminpage>
    </admin>
    
  <settings>
      <setting id="hide_strength_attributes" category="game" type="boolean" default="0" />
      <setting id="players_aging" category="game" type="select" selection="birthday,static" default="birthday" />
  </settings>
  
    <pages>
        <page
            id="player"
            template="player-details"
            model="PlayerDetailsWithDependenciesModel"
            role="user,guest"
            parentItem="team">
        </page>
        
        <page
            id="topstrikers"
            template="strikers"
            model="TopStrikersModel"
            role="user,guest"
            navitem="true"
            navweight="3"
            parentItem="leagues" />
        
        <page
            id="topscorers"
            template="scorers"
            model="TopScorersModel"
            role="user,guest"
            navitem="true"
            navweight="4"
            parentItem="leagues" />

    </pages> 
    
    <blocks>

        <block
            id="playerstatistics"
            template="playerstatistics"
            model="PlayerStatisticsModel"
            includepages="none"
            area="custom"
            role="user,guest" />
        
    </blocks>
    
</module>

=== ihofmann/open-websoccer/websoccer/modules/news/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
  
  <admin>
	<adminpage id="news" permissionrole="r_news" navcategory="website" entity="news">
		<entity dbtable="news AS NewsTab">
		    <overview edit="true" delete="true">
		    	<column id="entity_news_titel" type="text" field="NewsTab.titel" filter="true" sort="true" />
		    	<column id="entity_news_datum" type="timestamp" field="NewsTab.datum" sort="true"/>    
		    	<column id="entity_admin_name" type="text" field="AdminTab.name" filter="true" sort="true" />   
		    	<column id="entity_news_status" type="boolean" field="NewsTab.status" />   
		    	<join type="LEFT" jointable="admin AS AdminTab" joincondition="AdminTab.id = NewsTab.autor_id" />
		    </overview>
		    <editform>
		        <field id="autor_id" type="foreign_key" jointable="admin" entity="users" labelcolumns="name" required="true"/>
				<field id="titel" type="text" required="true" />
				<field id="datum" type="timestamp" required="true"/>
				<field id="nachricht" type="textarea" required="true" />
				<field id="linktext1" type="text" />
				<field id="linkurl1" type="url" />
				<field id="linktext2" type="text" />
				<field id="linkurl2" type="url" />
				<field id="linktext3" type="text" />
				<field id="linkurl3" type="url" />
				<field id="c_br" type="boolean" />
				<field id="c_links" type="boolean" />
				<field id="status" type="boolean" />        
		    </editform>
		    
		</entity>    
	</adminpage>
  </admin>
  
    <pages>
        <page
            id="news"
            model="NewsListModel"
            navitem="true"
            navweight="1"
            navmenukey="top"
            template="news-overview"
            role="guest,user">
	        <page
	            id="news-details"
	            model="NewsDetailsModel"
	            navitem="false"
	            template="news-details"
	            role="guest,user" />
        </page>
    </pages>
    
    <blocks>

        <block
            id="news"
            template="topnews"
            model="TopNewsListModel"
            includepages="home"
            area="custom"
            weight="0"
            role="guest,user" />
        
    </blocks>
</module>

=== ihofmann/open-websoccer/websoccer/modules/frontendads/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
    
    <settings>
    	<setting id="frontend_ads_hide_for_premiumusers" category="frontend" type="boolean" default="0" />
    	<setting id="frontend_ads_code_sidebar" category="frontend" type="textarea" />
    	<setting id="frontend_ads_code_top" category="frontend" type="textarea" />
    	<setting id="frontend_ads_code_bottom" category="frontend" type="textarea" />
	</settings>
  
    <blocks>

        <block
            id="ads_sidebar"
            template="ads_sidebar"
            model="AdsModel"
            includepages="all"
            area="sidebar"
            weight="10"
            role="user,guest" />
        
        <block
            id="ads_top"
            template="ads_top"
            model="AdsModel"
            includepages="all"
            area="content_top"
            weight="-10"
            role="user,guest" />
        
        <block
            id="ads_bottom"
            template="ads_bottom"
            model="AdsModel"
            includepages="all"
            area="content_bottom"
            weight="10"
            role="user,guest" />
        
    </blocks>

</module>

=== ihofmann/open-websoccer/websoccer/modules/formauthentication/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="userauthentication" version="1.0.0" />
        <dependency module="userregistration" version="1.0.0" />
    </dependencies>
    
    <pages>
        <page
            id="login"
            template="login"
            role="guest">
            <page
	            id="forgot-password"
	            template="forgot-password"
	            model="ForgotPasswordModel"
	            role="guest"/>
        </page>
        
        <page
            id="activate-user"
            template="activate-user"
            role="guest" />

    </pages>    
    
    <blocks>

        <block
            id="login-form"
            template="userlogin"
            includepages="all"
            excludepages="login,register"
            area="sidebar"
            weight="0"
            role="guest" />
        
    </blocks>
    
  <settings>
      <setting id="login_type" category="users" type="select" selection="email,username" default="email" />
      <setting id="login_method" category="users" type="text" default="DefaultUserLoginMethod" />
      <setting id="login_allow_sendingpassword" category="users" type="boolean" default="1" />
  </settings>
    
  <actions>
	<action id="login" controller="FormLoginController" role="guest">
		<param id="loginstr" type="text" required="true"/>
		<param id="loginpassword" type="text" required="true" max="32" />
		<param id="rememberme" type="boolean" />
	</action>
	
	<action id="send-password" controller="SendPasswordController" role="guest">
		<param id="useremail" type="text" required="true" validator="EmailValidator"/>
	</action>
	
	<action id="activate" controller="UserActivationController" role="guest">
		<param id="userid" type="number" required="true" />
		<param id="key" type="text" required="true" />
	</action>
  </actions>

</module>

=== ihofmann/open-websoccer/websoccer/modules/userabsence/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
  
  <admin>
	<adminpage id="userabsence" permissionrole="r_user" navcategory="website" entity="userabsence">
		<entity dbtable="userabsence AS AbsenceTab">
		    <overview edit="true" delete="true">
		    	<column id="entity_userabsence_user_id" type="text" field="UserTab.nick" filter="true" sort="true" />
		    	<column id="entity_userabsence_deputy_id" type="text" field="DeputyTab.nick" filter="true" sort="true" />
		    	<column id="entity_userabsence_from_date" type="timestamp" field="AbsenceTab.from_date" sort="true"/>    
		    	<column id="entity_userabsence_to_date" type="timestamp" field="AbsenceTab.to_date" sort="true"/> 
		    	
		    	<join type="INNER" jointable="user AS UserTab" joincondition="AbsenceTab.user_id = UserTab.id" />
		    	<join type="LEFT" jointable="user AS DeputyTab" joincondition="AbsenceTab.deputy_id = DeputyTab.id" />
		    </overview>
		    <editform>
		        <field id="user_id" type="foreign_key" entity="users" jointable="user" labelcolumns="nick" required="true" />
		        <field id="from_date" type="timestamp" required="true"/>
		        <field id="to_date" type="timestamp" required="true"/>
		        <field id="deputy_id" type="foreign_key" entity="users" jointable="user" labelcolumns="nick" />
		    </editform>
		    
		</entity>    
	</adminpage>
  </admin>
  
    <pages>
        <page
            id="absence"
            model="AbsenceModel"
            navitem="true"
            navweight="10"
            template="absence"
            parentItem="office"
            role="user">
        </page>
    </pages>
    
    <blocks>

        <block
            id="absence-alert"
            template="absence_alert"
            model="AbsenceAlertModel"
            includepages="office"
            area="content_top"
            weight="-1"
            role="user" />
        
    </blocks>
    
    <actions>
        <action id="report-absence"
            controller="ReportAbsenceController"
            role="user"
            log="true">
            <param id="days" type="number" required="true" min="2" max="30" />
            <param id="deputynick" type="text" required="true" />
        </action>
        
        <action id="return-from-absence"
            controller="ReturnFromAbsenceController"
            role="user"
            log="true"/>
        
    </actions>

</module>

=== ihofmann/open-websoccer/websoccer/modules/formation/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="office" version="1.0.0" />
        <dependency module="matches" version="1.0.0" />
    </dependencies>
    
    <settings>
      <setting id="formation_max_next_matches" category="game" type="number" default="3" />
      <setting id="formation_max_templates" category="game" type="number" default="10" />
    </settings>
    
    <pages>
        <page
            id="formation"
            template="formation"
            model="FormationModel"
            navitem="true"
            navweight="0"
            role="user"
            parentItem="office">
            
            
            
        </page>

    </pages> 
    
    <blocks>

        <block
            id="nextmatch_with_formationlink"
            template="nextmatch_with_formationlink"
            model="NextMatchModel"
            includepages="office"
            area="content_top"
            weight="0"
            role="user" />
        
        <block
            id="formation_templates"
            template="formation_templates"
            model="FormationTemplatesModel"
            includepages="none"
            area="custom"
            role="user" />
        
    </blocks>
    
  <actions>
	<action id="save-formation" controller="SaveFormationController" role="user" log="true">
	    <param id="id" type="number" required="true" />
	    
		<param id="offensive" type="number" required="true" min="1" max="100" />
		<param id="setup" type="text" required="true" />
		
		<param id="longpasses" type="boolean" />
		<param id="counterattacks" type="boolean" />
		<param id="freekickplayer" type="number" />
		
		<param id="player1" type="number" required="true" />
		<param id="player2" type="number" required="true" />
		<param id="player3" type="number" required="true" />
		<param id="player4" type="number" required="true" />
		<param id="player5" type="number" required="true" />
		<param id="player6" type="number" required="true" />
		<param id="player7" type="number" required="true" />
		<param id="player8" type="number" required="true" />
		<param id="player9" type="number" required="true" />
		<param id="player10" type="number" required="true" />
		<param id="player11" type="number" required="true" />
		<param id="bench1" type="number" />
		<param id="bench2" type="number" />
		<param id="bench3" type="number" />
		<param id="bench4" type="number" />
		<param id="bench5" type="number" />
		<param id="player1_pos" type="text" required="true" />
		<param id="player2_pos" type="text" required="true" />
		<param id="player3_pos" type="text" required="true" />
		<param id="player4_pos" type="text" required="true" />
		<param id="player5_pos" type="text" required="true" />
		<param id="player6_pos" type="text" required="true" />
		<param id="player7_pos" type="text" required="true" />
		<param id="player8_pos" type="text" required="true" />
		<param id="player9_pos" type="text" required="true" />
		<param id="player10_pos" type="text" required="true" />
		<param id="player11_pos" type="text" required="true" />
		
		<param id="sub1_out" type="number" />
		<param id="sub1_in" type="number" />
		<param id="sub1_minute" type="number"/>
		<param id="sub1_condition" type="text" />
		<param id="sub1_position" type="text" />
		
		<param id="sub2_out" type="number" />
		<param id="sub2_in" type="number" />
		<param id="sub2_minute" type="number" />
		<param id="sub2_condition" type="text" />
		<param id="sub2_position" type="text" />
		
		<param id="sub3_out" type="number" />
		<param id="sub3_in" type="number" />
		<param id="sub3_minute" type="number" />
		<param id="sub3_condition" type="text" />
		<param id="sub3_position" type="text" />
		
		<param id="templatename" type="text" max="24" />
	</action>
	
	<action id="remove-formation-template" controller="RemoveFormationTemplateController" role="user">
	    <param id="templateid" type="number" required="true" />
	</action>
  </actions>
    
</module>

=== ihofmann/open-websoccer/websoccer/modules/clubsrename/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
    
  <settings>
      <setting id="rename_club_enabled" category="game" type="boolean" default="0" />
  </settings>

    <pages>
        <page
            id="rename-club"
            template="rename_club"
            role="user"
            parentItem="team" />

    </pages> 
    
    <blocks>

        <block
            id="rename-club-link"
            template="rename_club_link"
            includepages="team"
            area="content_top"
            weight="0"
            role="user" />
        
    </blocks>
    
    <actions>
        <action id="rename-club" controller="RenameClubController" role="user" log="true">
        	<param id="name" type="text" required="true" min="8" max="24"/>    
        	<param id="kurz" type="text" required="true" min="3" max="4"/>    
        	<param id="stadium" type="text" required="true" min="8" max="24"/>
        </action>
        
    </actions>
</module>
